# Generated by Django 3.0.7 on 2020-10-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-date_created',), 'verbose_name': 'Projects', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ('-date_created',), 'verbose_name': 'Tags', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='tags',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='projects.Tags'),
        ),
    ]
